---
 - hosts: all
   become: true
   become_user: root
   tasks:
     - name: Installing below packages
       yum: name={{item}} state=latest
       with_items:
        - vim
        - wget
        - curl
